version: '3.3'
services:
    db:
        image: mysql:8.0
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: maker.2022
            MYSQL_DATABASE: integracion
            MYSQL_USER: pablo
            MYSQL_PASSWORD: admin
        volumes:
           - ./db-data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: maker.2022

    web:
        image: php:7.4-apache
        restart: always
        on:
          - db
        volumes:
            MYSQL_HOST: db
            MYSQL_DATABASE: integracion
            MYSQL_USER: pablo
            MYSQL_PASSWORD: admin

volumes:
    db-data: